In [5]:
%reload_ext sql
%config SqlMagic.autocommit=False
%config SqlMagic.autolimit=0
%config SqlMagic.autopandas=True
%config SqlMagic.displaylimit=200

In [6]:
%sql trino://localhost:9090/cuebiq/

'Connected: @cuebiq/'

In [7]:
pip install python-geohash

Requirement already satisfied: python-geohash in /srv/conda/envs/notebook/lib/python3.9/site-packages (0.8.5)
Note: you may need to restart the kernel to use updated packages.

In [8]:
import os
import time
import geohash
import logging
import pandas as pd
from sqlalchemy import create_engine
from datetime import datetime, timedelta

In [9]:
# SQL engine
from trino.dbapi import connect 
from sqlalchemy import create_engine

class TrinoEngine():
    def __init__(self):
        conn = connect(
            host="localhost",
            port=9090,
            catalog="cuebiq"
        )
        self.cur = conn.cursor()
        self.engine = create_engine("trino://localhost:9090/cuebiq/")
    
    def execute_statement(self, query:str) -> list:
        """
        Create and drop statements.
        """
        self.cur.execute(query)
        return self.cur.fetchall()
    
    def read_sql(self, query:str) -> pd.DataFrame: 
        """
        Select and insert into operations.
        """
        return pd.read_sql(query, self.engine)

sql_engine = TrinoEngine()

In [14]:
schema_name = {'cda': 'cuebiq.paas_cda_pe_v3'}
pe_tj_table = f"{schema_name['cda']}.trajectory_uplevelled"

# Set up logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# Database connection setup
output_schema_name = 'od_matrix20'
con = create_engine(f"trino://localhost:9090/dedicated/{output_schema_name}")

In [15]:
# Function to process data for a single day
def process_day(event_date, country_code, sql_engine):
    try:
        # Read data from the SQL table
        pe_tj_df = sql_engine.read_sql(
            f"""
            SELECT 
                cuebiq_id,
                start_lat,
                start_lng,
                end_lat,
                end_lng,
                duration_minutes,
                length_meters,
                number_of_points
            FROM cuebiq.paas_cda_pe_v3.trajectory_uplevelled
            WHERE 
                event_date = {event_date}
                AND end_country = '{country_code}' 
                AND start_country = '{country_code}' 
            """
        )
        logging.info(f"Executing SQL query for date {event_date}")

        # Encode geohashes
        pe_tj_df['start_geohash3'] = pe_tj_df.apply(
            lambda x: geohash.encode(x['start_lat'], x['start_lng'], precision=3), axis=1)
        pe_tj_df['end_geohash3'] = pe_tj_df.apply(
            lambda x: geohash.encode(x['end_lat'], x['end_lng'], precision=3), axis=1)

        # Add user numbers to the aggregated data
        aggregated_df3 = pe_tj_df.groupby(['start_geohash3', 'end_geohash3']).agg({
            'cuebiq_id': 'count',
            'duration_minutes': ['mean', 'median', 'std'],
            'length_meters': ['mean', 'median', 'std'],
            'number_of_points': ['mean', 'median', 'std']
        }).reset_index()
        aggregated_df3.columns = ['start_geohash3', 'end_geohash3', 'trip_count', 
                                  'm_duration_min', 'mdn_duration_min', 'sd_duration_min', 
                                  'm_length_m', 'mdn_length_m', 'sd_length_m',
                                  'm_points_no', 'mdn_points_no', 'sd_points_no']

        # Filter aggregated data and reorder columns
        filtered_df3= aggregated_df3.loc[aggregated_df3['trip_count'] > 9]
        filtered_df3 = filtered_df3[['start_geohash3', 'end_geohash3', 'trip_count', 
                                     'm_duration_min', 'mdn_duration_min', 'sd_duration_min', 
                                     'm_length_m', 'mdn_length_m', 'sd_length_m',
                                     'm_points_no', 'mdn_points_no', 'sd_points_no']]

        return filtered_df3

    except Exception as e:
        logging.error(f"Error processing data for date {event_date}: {e}")
        return pd.DataFrame()

# Function to insert data with retry mechanism
def insert_data_with_retry(df, table_name, con, retries=3, delay=5):
    for attempt in range(retries):
        try:
            df.to_sql(
                table_name, 
                con, 
                index=False, 
                if_exists="append", 
                method="multi"
            )
            logging.info(f"Inserted data into table {table_name}")
            break
        except Exception as e:
            logging.error(f"Attempt {attempt+1} failed with error: {e}")
            if attempt < retries - 1:
                time.sleep(delay)
            else:
                logging.error(f"Failed to insert data into table {table_name} after {retries} attempts")

# Main processing loop
def process_date_range(start_date, end_date, country_code, sql_engine):
    start_time = time.time()  # Record start time before processing loop
        
    current_date = start_date
    while current_date <= end_date:
        event_date = current_date.strftime('%Y%m%d')
        
        filtered_df3 = process_day(event_date, country_code, sql_engine)

        # Insert data into the database
        if not filtered_df3.empty:
            # table_name = f"{output_schema_name}.{country_code}_agg3"
            table_name = f"od_{country_code.lower()}_{event_date}_agg3_10"
            insert_data_with_retry(filtered_df3, table_name, con)
        else:
            logging.info(f"No data to insert for date {event_date}")

        # Move to the next day
        current_date += timedelta(days=1)
    end_time = time.time()  # Record end time after processing loop
    total_time = end_time - start_time
    logging.info(f"Total processing time: {total_time:.2f} seconds")

In [16]:
# Example usage:
process_date_range(datetime(2020, 1, 1), datetime(2020, 12, 31), 'CO', sql_engine)

2024-06-17 18:26:06,329 - INFO - Executing SQL query for date 20191101
2024-06-17 18:26:13,440 - INFO - Inserted data into table od_co_20191101_agg3_10
2024-06-17 18:26:25,792 - INFO - Executing SQL query for date 20191102
2024-06-17 18:26:32,371 - INFO - Inserted data into table od_co_20191102_agg3_10
2024-06-17 18:26:48,365 - INFO - Executing SQL query for date 20191103
2024-06-17 18:26:53,976 - INFO - Inserted data into table od_co_20191103_agg3_10
2024-06-17 18:27:07,797 - INFO - Executing SQL query for date 20191104
2024-06-17 18:27:13,042 - INFO - Inserted data into table od_co_20191104_agg3_10
2024-06-17 18:27:25,355 - INFO - Executing SQL query for date 20191105
2024-06-17 18:27:31,815 - INFO - Inserted data into table od_co_20191105_agg3_10
2024-06-17 18:27:44,275 - INFO - Executing SQL query for date 20191106
2024-06-17 18:27:50,223 - INFO - Inserted data into table od_co_20191106_agg3_10
2024-06-17 18:28:02,602 - INFO - Executing SQL query for date 20191107
2024-06-17 18:28:08,839 - INFO - Inserted data into table od_co_20191107_agg3_10
2024-06-17 18:28:22,743 - INFO - Executing SQL query for date 20191108
2024-06-17 18:28:29,165 - INFO - Inserted data into table od_co_20191108_agg3_10
2024-06-17 18:28:45,250 - INFO - Executing SQL query for date 20191109
2024-06-17 18:28:51,143 - INFO - Inserted data into table od_co_20191109_agg3_10
2024-06-17 18:29:03,624 - INFO - Executing SQL query for date 20191110
2024-06-17 18:29:09,019 - INFO - Inserted data into table od_co_20191110_agg3_10
2024-06-17 18:29:19,778 - INFO - Executing SQL query for date 20191111
2024-06-17 18:29:24,383 - INFO - Inserted data into table od_co_20191111_agg3_10
2024-06-17 18:29:36,854 - INFO - Executing SQL query for date 20191112
2024-06-17 18:29:42,949 - INFO - Inserted data into table od_co_20191112_agg3_10
2024-06-17 18:29:56,815 - INFO - Executing SQL query for date 20191113
2024-06-17 18:30:02,813 - INFO - Inserted data into table od_co_20191113_agg3_10
2024-06-17 18:30:19,946 - INFO - Executing SQL query for date 20191114
2024-06-17 18:30:26,402 - INFO - Inserted data into table od_co_20191114_agg3_10
2024-06-17 18:30:39,593 - INFO - Executing SQL query for date 20191115
2024-06-17 18:30:46,116 - INFO - Inserted data into table od_co_20191115_agg3_10
2024-06-17 18:30:58,553 - INFO - Executing SQL query for date 20191116
2024-06-17 18:31:04,100 - INFO - Inserted data into table od_co_20191116_agg3_10
2024-06-17 18:31:16,380 - INFO - Executing SQL query for date 20191117
2024-06-17 18:31:21,915 - INFO - Inserted data into table od_co_20191117_agg3_10
2024-06-17 18:31:35,016 - INFO - Executing SQL query for date 20191118
2024-06-17 18:31:40,374 - INFO - Inserted data into table od_co_20191118_agg3_10
2024-06-17 18:31:54,687 - INFO - Executing SQL query for date 20191119
2024-06-17 18:32:00,448 - INFO - Inserted data into table od_co_20191119_agg3_10
2024-06-17 18:32:13,412 - INFO - Executing SQL query for date 20191120
2024-06-17 18:32:18,465 - INFO - Inserted data into table od_co_20191120_agg3_10
2024-06-17 18:32:30,293 - INFO - Executing SQL query for date 20191121
2024-06-17 18:32:34,884 - INFO - Inserted data into table od_co_20191121_agg3_10
2024-06-17 18:32:47,872 - INFO - Executing SQL query for date 20191122
2024-06-17 18:32:52,984 - INFO - Inserted data into table od_co_20191122_agg3_10
2024-06-17 18:33:06,754 - INFO - Executing SQL query for date 20191123
2024-06-17 18:33:11,348 - INFO - Inserted data into table od_co_20191123_agg3_10
2024-06-17 18:33:21,320 - INFO - Executing SQL query for date 20191124
2024-06-17 18:33:24,979 - INFO - Inserted data into table od_co_20191124_agg3_10
2024-06-17 18:33:35,119 - INFO - Executing SQL query for date 20191125
2024-06-17 18:33:38,843 - INFO - Inserted data into table od_co_20191125_agg3_10
2024-06-17 18:33:54,016 - INFO - Executing SQL query for date 20191126
2024-06-17 18:33:57,961 - INFO - Inserted data into table od_co_20191126_agg3_10
2024-06-17 18:34:08,512 - INFO - Executing SQL query for date 20191127
2024-06-17 18:34:12,268 - INFO - Inserted data into table od_co_20191127_agg3_10
2024-06-17 18:34:22,051 - INFO - Executing SQL query for date 20191128
2024-06-17 18:34:26,317 - INFO - Inserted data into table od_co_20191128_agg3_10
2024-06-17 18:34:39,416 - INFO - Executing SQL query for date 20191129
2024-06-17 18:34:43,342 - INFO - Inserted data into table od_co_20191129_agg3_10
2024-06-17 18:34:55,389 - INFO - Executing SQL query for date 20191130
2024-06-17 18:34:59,236 - INFO - Inserted data into table od_co_20191130_agg3_10
2024-06-17 18:35:09,193 - INFO - Executing SQL query for date 20191201
2024-06-17 18:35:13,488 - INFO - Inserted data into table od_co_20191201_agg3_10
2024-06-17 18:35:24,221 - INFO - Executing SQL query for date 20191202
2024-06-17 18:35:27,903 - INFO - Inserted data into table od_co_20191202_agg3_10
2024-06-17 18:35:38,287 - INFO - Executing SQL query for date 20191203
2024-06-17 18:35:41,983 - INFO - Inserted data into table od_co_20191203_agg3_10
2024-06-17 18:35:55,830 - INFO - Executing SQL query for date 20191204
2024-06-17 18:36:00,506 - INFO - Inserted data into table od_co_20191204_agg3_10
2024-06-17 18:36:11,567 - INFO - Executing SQL query for date 20191205
2024-06-17 18:36:15,345 - INFO - Inserted data into table od_co_20191205_agg3_10
2024-06-17 18:36:26,540 - INFO - Executing SQL query for date 20191206
2024-06-17 18:36:30,819 - INFO - Inserted data into table od_co_20191206_agg3_10
2024-06-17 18:36:44,104 - INFO - Executing SQL query for date 20191207
2024-06-17 18:36:48,007 - INFO - Inserted data into table od_co_20191207_agg3_10
2024-06-17 18:36:57,646 - INFO - Executing SQL query for date 20191208
2024-06-17 18:37:00,869 - INFO - Inserted data into table od_co_20191208_agg3_10
2024-06-17 18:37:14,580 - INFO - Executing SQL query for date 20191209
2024-06-17 18:37:18,229 - INFO - Inserted data into table od_co_20191209_agg3_10
2024-06-17 18:37:28,366 - INFO - Executing SQL query for date 20191210
2024-06-17 18:37:32,346 - INFO - Inserted data into table od_co_20191210_agg3_10
2024-06-17 18:37:42,237 - INFO - Executing SQL query for date 20191211
2024-06-17 18:37:46,008 - INFO - Inserted data into table od_co_20191211_agg3_10
2024-06-17 18:37:57,873 - INFO - Executing SQL query for date 20191212
2024-06-17 18:38:01,891 - INFO - Inserted data into table od_co_20191212_agg3_10
2024-06-17 18:38:12,309 - INFO - Executing SQL query for date 20191213
2024-06-17 18:38:16,089 - INFO - Inserted data into table od_co_20191213_agg3_10
2024-06-17 18:38:29,138 - INFO - Executing SQL query for date 20191214
2024-06-17 18:38:32,894 - INFO - Inserted data into table od_co_20191214_agg3_10
2024-06-17 18:38:42,819 - INFO - Executing SQL query for date 20191215
2024-06-17 18:38:46,397 - INFO - Inserted data into table od_co_20191215_agg3_10
2024-06-17 18:38:56,077 - INFO - Executing SQL query for date 20191216
2024-06-17 18:38:59,684 - INFO - Inserted data into table od_co_20191216_agg3_10
2024-06-17 18:39:11,975 - INFO - Executing SQL query for date 20191217
2024-06-17 18:39:15,818 - INFO - Inserted data into table od_co_20191217_agg3_10
2024-06-17 18:39:25,787 - INFO - Executing SQL query for date 20191218
2024-06-17 18:39:29,316 - INFO - Inserted data into table od_co_20191218_agg3_10
2024-06-17 18:39:40,112 - INFO - Executing SQL query for date 20191219
2024-06-17 18:39:44,028 - INFO - Inserted data into table od_co_20191219_agg3_10
2024-06-17 18:39:57,602 - INFO - Executing SQL query for date 20191220
2024-06-17 18:40:02,154 - INFO - Inserted data into table od_co_20191220_agg3_10
2024-06-17 18:40:14,159 - INFO - Executing SQL query for date 20191221
2024-06-17 18:40:18,091 - INFO - Inserted data into table od_co_20191221_agg3_10
2024-06-17 18:40:28,139 - INFO - Executing SQL query for date 20191222
2024-06-17 18:40:31,969 - INFO - Inserted data into table od_co_20191222_agg3_10
2024-06-17 18:40:42,385 - INFO - Executing SQL query for date 20191223
2024-06-17 18:40:47,685 - INFO - Inserted data into table od_co_20191223_agg3_10
2024-06-17 18:41:03,482 - INFO - Executing SQL query for date 20191224
2024-06-17 18:41:08,117 - INFO - Inserted data into table od_co_20191224_agg3_10
2024-06-17 18:41:16,691 - INFO - Executing SQL query for date 20191225
2024-06-17 18:41:20,431 - INFO - Inserted data into table od_co_20191225_agg3_10
2024-06-17 18:41:30,866 - INFO - Executing SQL query for date 20191226
2024-06-17 18:41:34,799 - INFO - Inserted data into table od_co_20191226_agg3_10
2024-06-17 18:41:46,416 - INFO - Executing SQL query for date 20191227
2024-06-17 18:41:50,664 - INFO - Inserted data into table od_co_20191227_agg3_10
2024-06-17 18:42:04,817 - INFO - Executing SQL query for date 20191228
2024-06-17 18:42:08,927 - INFO - Inserted data into table od_co_20191228_agg3_10
2024-06-17 18:42:17,753 - INFO - Executing SQL query for date 20191229
2024-06-17 18:42:21,708 - INFO - Inserted data into table od_co_20191229_agg3_10
2024-06-17 18:42:33,539 - INFO - Executing SQL query for date 20191230
2024-06-17 18:42:37,592 - INFO - Inserted data into table od_co_20191230_agg3_10
2024-06-17 18:42:46,350 - INFO - Executing SQL query for date 20191231
2024-06-17 18:42:49,799 - INFO - Inserted data into table od_co_20191231_agg3_10
2024-06-17 18:42:49,800 - INFO - Total processing time: 1019.05 seconds